name: CI Demo

on:
  workflow_dispatch:
    inputs:
      DEMO_ENV:
        description: "Demo environment name"
        required: true
env:
  DEMO_ENV: ${{ github.event.inputs.DEMO_ENV }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Check Python version
        run: python --version
      - name: Run Python script
        id: run_python
        run: echo "Python setup completed"

      # 4️⃣ Setup Java
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Check Java version
        run: java -version
      - name: Run build
        run: echo "Build completed"
      - name: run java script
        id: run_java
        run: echo "Java setup completed"
      - name: Display Environment Variable
        run: echo "The demo environment is $DEMO_ENV"