name: access env variables

on:
  push:
    branches:
      - main

jobs:
  demo-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display Org / Repo / Env Variable
        run: |
          echo "Company is ${{ vars.COMPANY_NAME }}"
